name: pitik_internal_app
version: 5.2.1+122
publish_to: none
description: Pitik Internal App for manage downstream team
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  autocomplete_textfield: ^2.0.1
  build_runner: ^2.4.4
  built_value_generator: ^8.5.0
  chucker_flutter: ^1.5.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  dropdown_button2: ^2.1.2
  file_picker: ^5.3.0
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.3.0
  firebase_messaging: ^14.6.0
  firebase_remote_config: ^4.2.0
  fl_location: ^2.0.0+1
  flutter_flavorizr: ^2.1.5
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^15.1.1
  flutter_masked_text2: ^0.9.1
  flutter_picker: ^2.1.0
  flutter_svg: ^2.0.0+1
  get: ^4.6.5
  getwidget: ^4.0.0
  google_sign_in: ^6.1.0
  http: ^1.1.0
  image: ^4.0.17
  image_picker: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  lottie: ^2.3.2
  mask_text_input_formatter: ^2.5.0
  mixpanel_flutter: ^2.1.1
  mobile_number: ^2.1.1
  open_store: ^0.5.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.0
  pdf: ^3.10.4
  permission_handler: ^11.0.0
  qr_code_scanner: ^1.0.1
  reflectable: ^4.0.5
  restart_app: ^1.2.1
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0
  shorebird_code_push: ^1.1.0
  sign_in_with_apple: ^4.3.0
  sqflite: ^2.3.2
  syncfusion_flutter_charts: ^22.2.12
  url_launcher: ^6.1.12
  components: 
    path: ../components
  dao_impl: 
    path: ../dao_impl
  engine: 
    path: ../engine
  flutter: 
    sdk: flutter
  global_variable: 
    path: ../global_variable
  google_plus_code: 
    git: https://github.com/anggasetiawanw/google_plus_code.git
  model: 
    path: ../model
dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^1.0.4
  flutter_test: 
    sdk: flutter
flavorizr: 
  app: 
    android: 
      flavorDimensions: flavor-type
  flavors: 
    prod: 
      app: 
        name: Pitik Internal App
      android: 
        applicationId: id.pitik.mobile.mobile_flutter
        icon: images/launcher_pitik.png
        resValues: 
          uri: 
            type: string
            value: https://api.pitik.id/
          crashlytic: 
            type: string
            value: PRODUCTION
        firebase: 
          config: android/app/src/prod/google-services.json
      ios: 
        bundleId: id.pitik.mobile.mobileFlutter
        icon: ios/config/Launcher.png
        variables: 
          uri: 
            value: https://api.pitik.id/
          crashlytic: 
            value: PRODUCTION
        firebase: 
          config: ios/config/prod/GoogleService-Info.plist
    dev: 
      app: 
        name: Pitik Internal App - Staging
      android: 
        applicationId: id.pitik.mobile.mobile_flutter.staging
        icon: ios/config/staging_launcher.png
        resValues: 
          uri: 
            type: string
            value: https://api.pitik.dev/
          crashlytic: 
            type: string
            value: STAGING
        firebase: 
          config: android/app/src/dev/google-services.json
      ios: 
        bundleId: id.pitik.mobile.mobileFlutter.staging
        icon: images/launcher_pitik.png
        variables: 
          uri: 
            value: https://api.pitik.dev/
          crashlytic: 
            value: STAGING
        firebase: 
          config: ios/config/dev/GoogleService-Info.plist
flutter_icons: 
  image_path: images/launcher_pitik.png
  android: true
  ios: true
flutter: 
  assets: 
    - images/
    - json/
    - shorebird.yaml
  fonts: 
    - 
      family: Montserrat_Bold
      fonts: 
        - 
          asset: font/montserrat_bold.ttf
    - 
      family: Montserrat_Medium
      fonts: 
        - 
          asset: font/montserrat_medium.ttf
  uses-material-design: true
