name: components
description: Components Pitik Library
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  engine:
    path: ../engine
  model:
    path: ../model
  dao_impl:
    path: ../dao_impl
  global_variable:
    path: ../global_variable
  flutter_lints: ^2.0.0
  permission_handler: ^11.0.0
  internet_connection_checker: ^1.0.0+1
  chucker_flutter: ^1.5.1
  build_runner: ^2.4.4
  built_value_generator: ^8.5.0
  reflectable: ^4.0.5
  mixpanel_flutter: ^2.1.1
  firebase_crashlytics: ^3.3.0
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.0
  sqflite: ^2.2.8+3
  firebase_remote_config: ^4.2.0
  firebase_core: ^2.12.0
  path_provider: ^2.1.0
  http: ^1.1.0
  fl_location: ^2.0.0+1
  flutter_reactive_ble: ^5.2.0
  mobile_number: ^2.1.1
  image: ^4.0.17
  get: ^4.6.5
  flutter_masked_text2: ^0.9.1
  flutter_svg: ^2.0.0+1
  mask_text_input_formatter: ^2.5.0
  qr_code_scanner: ^1.0.1
  getwidget: ^4.0.0
  lottie: ^2.3.2
  syncfusion_flutter_charts: ^22.2.12
  dropdown_button2: ^2.1.2
  flutter_picker: ^2.1.0
  image_picker: ^1.0.2
  file_picker: ^5.3.0
  autocomplete_textfield: ^2.0.1
  currency_text_input_formatter: ^2.1.10
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^4.3.0
  firebase_auth: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
